// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1nEKlj4OpttDLK_PbGbCvmEeAltI93wk',
    appId: '1:56397164707:web:5ea137e9cf569e47958f16',
    messagingSenderId: '56397164707',
    projectId: 'my-task-f4c6e',
    authDomain: 'my-task-f4c6e.firebaseapp.com',
    storageBucket: 'my-task-f4c6e.appspot.com',
    measurementId: 'G-HMEMPK4L8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaSsH5RRoCWYhmDioLfAasUnMUHMsDG3I',
    appId: '1:56397164707:android:905c571163b95f47958f16',
    messagingSenderId: '56397164707',
    projectId: 'my-task-f4c6e',
    storageBucket: 'my-task-f4c6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhmQx0pLUl1-DFPQonOw-jVbM_19CteU8',
    appId: '1:56397164707:ios:cf81a5e9a36a82c7958f16',
    messagingSenderId: '56397164707',
    projectId: 'my-task-f4c6e',
    storageBucket: 'my-task-f4c6e.appspot.com',
    iosClientId: '56397164707-un5499g4q6i382fhknnto4inajve874j.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhmQx0pLUl1-DFPQonOw-jVbM_19CteU8',
    appId: '1:56397164707:ios:cf81a5e9a36a82c7958f16',
    messagingSenderId: '56397164707',
    projectId: 'my-task-f4c6e',
    storageBucket: 'my-task-f4c6e.appspot.com',
    iosClientId: '56397164707-un5499g4q6i382fhknnto4inajve874j.apps.googleusercontent.com',
    iosBundleId: 'com.example.task',
  );
}
